### ISSUE TITLE
Loss of information when exporting to JSON

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/Kami-JS#4]
Attributes on nodes that have the same name will get their parents re-assigned when exporting to JSON. For example, the following graph:
![capture](https://cloud.githubusercontent.com/assets/1588553/19167877/9ab1edbc-8bdb-11e6-8375-5e0c3b7e9568.PNG)

Becomes the following JSON, where the rate attributes are now pointing to the same entity on the tree:

```
{"version":2.0,
 "agents":[
{"classes":["agent"],"father_classes":[],"path":[],"labels":["C"],"values":[],"x":474,"y":252},
{"classes":["agent"],"father_classes":[],"path":[],"labels":["D"],"values":[],"x":802,"y":248},
{"classes":["agent"],"father_classes":[],"path":[],"labels":["A"],"values":[],"x":474,"y":139},
{"classes":["agent"],"father_classes":[],"path":[],"labels":["B"],"values":[],"x":809,"y":127}
],
 "regions":[
],
 "key_rs":[
],
 "attributes":[
{"classes":["attribute","list"],"father_classes":["action","bnd","revers"],"path":["rev-bind"],"labels":["rate"],"values":["2.0"],"x":620.0760961020505,"y":323.9735501703761},
{"classes":["attribute","list"],"father_classes":["action","bnd","revers"],"path":["rev-bind"],"labels":["rate"],"values":["1.0"],"x":620.093746391759,"y":161.53215372790945}
],
 "flags":[
],
 "actions":[
{"classes":["action","bnd","revers"],"labels":["rev-bind"],
"left":[{"ref":["agents",0]}],
"right":[{"ref":["agents",1]}],
"context":[],
"x":596,"y":275.51666259765625},
{"classes":["action","bnd","revers"],"labels":["rev-bind"],
"left":[{"ref":["agents",2]}],
"right":[{"ref":["agents",3]}],
"context":[],
"x":585,"y":123}
]
}
```

When read back, Kami displays the following graph, where the rate attribute got its parent re-assigned:
![capture](https://cloud.githubusercontent.com/assets/1588553/19167960/e93d163c-8bdb-11e6-8f1e-3a7513acc34f.PNG)

This means the modeler must rename the actions with globally unique labels when writing the "local" nuggets, which is not feasible outside toy models.

**Comment by abassobl** [comment]
I added an auto increment for actions, in order to have unique label on actions with default name
