### ISSUE TITLE
Action attributes attracted to top-left corner very strongly

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/Kami-JS#5]
With all nodes unlocked, attributes of actions are attracted to the canvas' top-left corner, and pull in that direction the rest of the graph & connected components.
![capture](https://cloud.githubusercontent.com/assets/1588553/19171496/1c553c3e-8beb-11e6-96a9-60632734c27a.PNG)

Since one can not lock these attribute nodes into position, they often end up divorced from their parent node, sometimes gravitating to positions behind other nodes, making large graphs impossible to organize.

**Comment by abassobl** [comment]
In fact they are attracted by the gravity field of the SVG. I reduced the attractivity and reduce link size, but this behavior will stay until I change the full SVG implementation.
So in order to solve that, as a workarroud, I added the possibility to fixe attributes position.
