### ISSUE TITLE
Aesthetic: Link-right & link-left impose chirality on a non-chiral graph

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/Kami-JS#6]
Using link-left and link-right to connect action boxes to agents makes it awkward to re-arrange agents. When importing a large amount of nuggets, re-arranging is crucial to visualizing the graph. Unless the modeler has the foresight to link-left & link-right with a global perspective, the graphs become "tangled".

Unless link-left & link-right will be deprecated, I would suggest adding a "flip link-right & link-left" to an action's context menu, so that the modeler can alter this visual/logic element.

**Comment by abassobl** [comment]
flip added !
